{:dev-env-vars  {:env  {:database-url               "jdbc:mysql://root:123456@172.17.0.1:4442/bolha_musical?useLegacyDatetimeCode=false&serverTimezone=Etc/UCT"
                        :rocket-chat-base-url       "http://localhost:3080"
                        :spotify-client-id          "sdasdsadasdsadsadsadasdsadsadasdsa"
                        :spotify-client-secret      "sadasdasdasdasdsadsadsadasdsadsadsasad"
                        :spotify-auth-encoded       "Basic sssssssssssssssssssssssssssssssssssssssssssssssssss="
                        :spotify-redirect-uri       "http://10.0.0.108:3001/api/v1/spotify/login/callback"
                        :sendinblue-user-login      "root"
                        :sendinblue-user-password   "123456"
                        :auth-key                   "xsfafsssssssssssssssssssssssssssssssssssssssssssssssssssssss"
                        :redis-url                  "redis://172.17.0.1:9475"
                        :rocket-chat-admin-id       "aasdsdsadsadsadas"
                        :rocket-chat-admin-username "user"
                        :rocket-chat-admin-password "123456"}
                 :ring {:open-browser? false}}
 :test-env-vars {:env {:database-url             "jdbc:mysql://root:123456@172.17.0.1:4443/bolha_musical"
                       :spotify-client-id        "sdfdsfsddddddddddddfdsfsdfsdfsdf"
                       :spotify-client-secret    "11111111111111111111111111111"
                       :spotify-auth-encoded     "Basic MDAxMmY4MmE4MjQ="
                       :spotify-redirect-uri     "http://10.0.0.108:3001/api/spotify/login/callback"
                       :sendinblue-user-login    "root"
                       :sendinblue-user-password "123456"
                       :auth-key                 ""
                       }}}